services:
  robot_state_publisher:
    build:
      context: .
      dockerfile: containers/robot_state_publisher/Dockerfile
    volumes:
      - ./urdf:/urdf:ro
      - ./config:/config:ro
      - ./data:/data
    environment:
      - ROS_DOMAIN_ID=87
      - "RCUTILS_CONSOLE_OUTPUT_FORMAT=[{severity}] [{time}]: {message}"

  fuzzer:
    build:
      context: .
      dockerfile: containers/fuzzer/Dockerfile
    volumes:
      - ./config:/config:ro
      - ./data:/data
    environment:
      - ROS_DOMAIN_ID=87
      - PYTHONUNBUFFERED=1
    depends_on:
      - robot_state_publisher

  recorder:
    build:
      context: .
      dockerfile: containers/recorder/Dockerfile
    volumes:
      - ./config:/config:ro
      - ./data:/data
    environment:
      - ROS_DOMAIN_ID=87
      - PYTHONUNBUFFERED=1
    depends_on:
      - robot_state_publisher

  visualizer:
    build:
      context: .
      dockerfile: containers/visualizer/Dockerfile
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8000:8000"
    environment:
      - ROS_DOMAIN_ID=87
    depends_on:
      - robot_state_publisher